# Generated by Django 4.2.7 on 2023-11-30 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_category_image_category_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='price',
        ),
    ]
